### ISSUE TITLE
image in text clickable

### ISSUE THREAD

**Issue by ch-sander** [lombardpress/lombardpress-webjs#109]
Maybe it would make sense that the image in a text is clickable leading to the same event as clicking on the line number (which makes sense for text, but images are not thought of in terms on 'lines' -- this is rather an artefact of the XML...which is fine but could be coped by hyperlinking the image itself)

**Comment by ch-sander** [comment]
also show image metadata in info panel

**Comment by jeffreycwitt** [comment]
I think this is resolved as of commit 197085b15baffda4aada7c1849e23d695c651782
