### ISSUE TITLE
Searching texts

### ISSUE THREAD

**Issue by ch-sander** [lombardpress/lombardpress-webjs#111]
I would be nice to have a search for all texts at "A Top Level Work Group for all Work Groups in the SCTA"

**Comment by jeffreycwitt** [comment]
I think this is already possible: 

The search parameters adjust as you move through different work groups or expressions. 

For example at the SCTA top level, the user can search the entire corpus: 

<img width="1626" alt="image" src="https://user-images.githubusercontent.com/1146685/169922516-b566e23a-d5c1-449e-8962-02e35e636aec.png">

But when the select a sub work group the parameter change and now the search group is restricted to that work group. For example, here I'm focused on Sentences Commentaries and the search parameter has changed.

<img width="1626" alt="image" src="https://user-images.githubusercontent.com/1146685/169922574-882a51a1-08be-4ad1-9471-32c56997aae7.png">

**Comment by ch-sander** [comment]
You are right -- no idea how I missed this!
