### ISSUE TITLE
Bottom window preventing view of text

### ISSUE THREAD

**Issue by jeffreycwitt** [lombardpress/lombardpress-webjs#63]
Bottom window preventing view of text; 

When bottom window is open text component should probably additional padding so that the scroll can continue

**Comment by jeffreycwitt** [comment]
@uzahnd I think I've resolved the bottom window scroll; please confirm that you're now able to scroll to the bottom of the text when the bottom window panel is open. 

I close issue after your confirmation

**Comment by uzahnd** [comment]
confirmed: it works now in the text panel (but the same issue still remains for the citation panel, which is less important, however)

**Comment by jeffreycwitt** [comment]
I can't recreate the problem with the "citation panel" / side window. You'll have to show me that next time we meet :)
